### ISSUE TITLE
Scrollbar should also be on top of table

### ISSUE THREAD

**Issue by enmust** [geocollections/eurocore-db-ui#21]
Because sometimes tables are too big and instead of scrolling to the bottom of page it would be more convenient to just move the table from the top

**Comment by enmust** [comment]
https://github.com/avianey/jqDoubleScroll/blob/master/README.md

**Comment by enmust** [comment]
Dropped that functionality

**Comment by urtson** [comment]
Reopen this, needed in drillcore data view. If more than 4 parameters are selected, you have to start scrolling horizontally but first you have to scroll down which is unconvenient.

**Comment by enmust** [comment]
Tested this library and some others but didn't find a good solution, so I came up with a different solution.
