### ISSUE TITLE
links/keys to move to next box in drillcore box detail view

### ISSUE THREAD

**Issue by ollehints** [geocollections/eurocore-db-ui#3]
In drillcore box detail view (https://eurocore.rocks/#/corebox/2) user should be able to easily move to previous/next box. Links "next box" and "previous box" + maybe also keyboard L and R arrows.
For testing this could be done using box ID but otherwise it should work within the range of boxes of one drillcore.
"L-" in drillcore numbers is redundant as it simply denotes "box-" (Laatikko in Finnish).

**Comment by urtson** [comment]
In drillcore view core boxes tab the box header should look then Box: 1
like in drillcore box detail view

**Comment by enmust** [comment]
Added word 'Box'

**Comment by enmust** [comment]
Now works using box ID, but for this to work within the range of boxes of one drillcore I would need extra data. For example drillcore table could have first_box_id and and last_box_id fields

**Comment by enmust** [comment]
Probably need array of ids because box images ids do not come in succession. 
Closing this issue now.
