### ISSUE TITLE
Credits on map

### ISSUE THREAD

**Issue by ollehints** [geocollections/eurocore-db-ui#32]
Bedrock age: [IGME 5000](https://www.bgr.bund.de/EN/Themen/Sammlungen-Grundlagen/GG_geol_Info/Karten/International/Europa/IGME5000/IGME_Project/IGME_Projectinfo.html?nn=1556388).
Rocks of Finland: [Geological Survey of Finland](http://gtk.fi).

**Comment by enmust** [comment]
Done
