### ISSUE TITLE
Preview images need new urls

### ISSUE THREAD

**Issue by urtson** [geocollections/eurocore-db-ui#39]
As images come now from new location, the urls of preview images are changed. Therefore drillcore box previews are not loaded right now.

/files/53/1000/53e20a8e-2bfc-4bc1-b2b4-bed900c8625c.jpg
comes to
/files/medium/53/e2/53e20a8e-2bfc-4bc1-b2b4-bed900c8625c.jpg

former 400->small, 1000->medium, 2000->large

**Comment by enmust** [comment]
Done
