### ISSUE TITLE
Structures tab description updated

### ISSUE THREAD

**Issue by urtson** [geocollections/eurocore-db-ui#40]
Updated the description of 'Structures' tab of drillcore view in dropbox, can be implemented.
Some example data is now available in database
https://api.eurocore.rocks/structure/

**Comment by enmust** [comment]
drillcore_summary table should be updated currently structures is null

**Comment by urtson** [comment]
Updated

**Comment by enmust** [comment]
It is okay on test drillcore but shouldn't it follow the same logic like in others. I mean if there is no structures the value should be 0 not null.

**Comment by urtson** [comment]
Added zeroes
