### ISSUE TITLE
Corebox view issues

### ISSUE THREAD

**Issue by urtson** [geocollections/eurocore-db-ui#42]
https://eurocore.rocks/#/corebox/30

1. In chart tab too many parameters are displayed that do not belong to this drillcore. It seems happen when no analysis method is specified for analyses from thatt drillcore. Ok in Kylylahti 223
2. In Samples and Analyses tabs the table header is not loaded correctly- sometimes it does not appear before you start scrolling

**Comment by enmust** [comment]
This header problem comes from jquery floathead plugin. I don't know exactly what causes it yet. Somehow the header gets wrong Y coordinate and it thinks user has already scrolled and if you start scrolling then it corrects itself.

**Comment by enmust** [comment]
Should change jquery floathead plugin to something similar https://tallent.us/vue-scrolling-table/

**Comment by urtson** [comment]
p.1 still needs attention. As the analysis_method is not specified, only Au ppm should be displayed on chart. Also, as results are in ppm, % axis should not displayed.

**Comment by enmust** [comment]
Should use same solution like in #21

**Comment by enmust** [comment]
Opened new issue about chart methods problem
