### ISSUE TITLE
Display attached files in analysis detail window

### ISSUE THREAD

**Issue by urtson** [geocollections/eurocore-db-ui#43]
for displaying attached data, especially for 3D scans
Image previews based on attachment type and mime type
Link to raw data file if is data file type

https://api.eurocore.rocks/attachment/?analysis__id=2040001

**Comment by urtson** [comment]
Works, was just permission issue

**Comment by urtson** [comment]
Reopened this as we need a link for downloading raw data file.
If a data file exists, Raw data section is displayed where original filename appears along with download button

**Comment by urtson** [comment]
Raw data section should appear on the right, below slices

**Comment by urtson** [comment]
Added some real data, see https://eurocore.rocks/#/analysis/977

1. Slices should be filtered by attachment_type__value, then only images are shown. Currently data files also appear there because they are in tiff format
2. Links get too long in Raw data section, better use title field instead of original_filename
3. Rename Raw data to Stacked images
4. Add a field Drillcore to details table, content from drillcore__name

**Comment by enmust** [comment]
Updated

**Comment by urtson** [comment]
Drillcore field now appears twice in other analyses detail view
https://eurocore.rocks/#/analysis/294
Didn't check how it was before, maybe it was missing only in CT scan view
In CT scan it should be placed after ID field.

**Comment by enmust** [comment]
Should be ok
