### ISSUE TITLE
Show drillcore diameter in CT scan view

### ISSUE THREAD

**Issue by urtson** [geocollections/eurocore-db-ui#55]
In analysis detail view, when analysis method is CT, show additional field 'Core diameter' in the table after 'Depth to' field. Data is loaded by additional query https://api.eurocore.rocks/drillcore_diameter/?drillcore__id=17&start_depth__lte=78.96&end_depth__gte=79.02

Can be tested by https://eurocore.rocks/#/analysis/2040001, private record

**Comment by enmust** [comment]
I added 'drillcore__diameter' field to analysis table or should I use this additional query?

**Comment by urtson** [comment]
Better use the additional query as as the diameter may change along the drillcore. 'drillcore__diameter' will not show the right number at the certain depth of analysis, see a test example for Vaara drillcore
https://api.eurocore.rocks/analysis/3220

Right query for this analysis is https://api.eurocore.rocks/drillcore_diameter/?drillcore__id=16&start_depth__lte=100&end_depth__gte=101
